# Site
repository: ramdevji.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Ramdev Godara
title: Software Developer
email: godaraji47@gmail.com
phone: +918502005745

# Social links
github_username:  https://github.com/ramdevji
linkedin_username: https://www.linkedin.com/in/ramdev-g-14781110a/


# About Section
about_title: Software Developer
about_profile_image: _test/images/travis.png
about_content: > # this means to ignore newlines until the next config item.
  I am a software developer with over 3 years of industry experience in various tech stacks, 
  including Python, Java, AWS, Redis, PostgreSQL, and Jenkins. I am confident and excited to 
  solve challenging problems. Let's connect.

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

data_dir: _test/_data

include:
 - _test

exclude:
  - vendor

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
